In [1]:
import numpy as np

In [2]:
a=np.array([20,90,56,45,12,10])

In [3]:
a

array([20, 90, 56, 45, 12, 10])

In [12]:
np.median(a)

32.5

In [4]:
np.mean(a)

38.833333333333336

In [5]:
p=np.mean(a)

In [7]:
round(p,2)

38.83

In [8]:
b=np.array([10,20,30,40,50,60,70])

In [9]:
b


array([10, 20, 30, 40, 50, 60, 70])

In [10]:
np.mean(b)

40.0

In [11]:
np.median(b)

40.0

In [13]:
a

array([20, 90, 56, 45, 12, 10])

In [14]:
a.min()

10

In [15]:
a.max()

90

In [16]:
range_of_a=a.max()-a.min()

In [17]:
range_of_a

80

In [19]:
a

array([20, 90, 56, 45, 12, 10])

In [20]:
a.var()

809.4722222222222

In [21]:
a.std()

28.451225320225177

In [22]:
round(a.std(),2)

28.45

In [23]:
b

array([10, 20, 30, 40, 50, 60, 70])

In [24]:
b.var()

400.0

In [25]:
b.std()

20.0